// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Unpooled connection string for the shadow database Prisma uses during
    // `migrate dev`. DIRECT_URL is the generic name; DATABASE_URL_UNPOOLED is
    // what Neon's Vercel integration provides out of the box.
    shadowDatabaseUrl:
      process.env["DIRECT_URL"] || process.env["DATABASE_URL_UNPOOLED"],
  },
});
