// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Optional: an unpooled connection string for the shadow database Prisma
    // uses during `migrate dev`, if your Postgres provider gives you a pooled
    // DATABASE_URL (e.g. via PgBouncer). Falls back to DATABASE_URL if unset.
    shadowDatabaseUrl: process.env["DIRECT_URL"],
  },
});
